# 7 - implemmentation of one versus one and one Versus rest schemes with support vector machine

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
from sklearn import svm , datasets
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import classification_report , confusion_matrix 

In [7]:
# datasets 

iris = datasets.load_iris()
# iris

In [9]:
# extract 2 coolumns 

X = iris.data[ : , :2]
y = iris.target

In [10]:
# split data 

X_train , X_test , y_train , y_test = train_test_split(X , y , test_size = 0.3 , random_state = 0)

# radial Basis kernel

In [11]:
rbf = SVC(kernel = 'rbf' , gamma = 1 , decision_function_shape = 'ovo')

In [12]:
rbf.fit(X_train , y_train)

SVC(decision_function_shape='ovo', gamma=1)

In [13]:
y_pred = rbf.predict(X_test)

In [14]:
print("RBF kernel One vs One ")

confusion_matrix(y_test , y_pred)

RBF kernel One vs One 


array([[16,  0,  0],
       [ 0, 10,  8],
       [ 0,  2,  9]], dtype=int64)

In [15]:
classification_report(y_test , y_pred)

'              precision    recall  f1-score   support\n\n           0       1.00      1.00      1.00        16\n           1       0.83      0.56      0.67        18\n           2       0.53      0.82      0.64        11\n\n    accuracy                           0.78        45\n   macro avg       0.79      0.79      0.77        45\nweighted avg       0.82      0.78      0.78        45\n'

# Linear kernel 

In [16]:
linear = SVC(kernel = 'linear' , gamma = 1 , decision_function_shape = 'ovo')

In [17]:
linear.fit(X_train , y_train)

SVC(decision_function_shape='ovo', gamma=1, kernel='linear')

In [18]:
y_pred = linear.predict(X_test)

In [19]:
print("Linear kernel one vs one")

confusion_matrix(y_test , y_pred)

Linear kernel one vs one


array([[16,  0,  0],
       [ 0, 13,  5],
       [ 0,  4,  7]], dtype=int64)

In [20]:
classification_report(y_test , y_pred)

'              precision    recall  f1-score   support\n\n           0       1.00      1.00      1.00        16\n           1       0.76      0.72      0.74        18\n           2       0.58      0.64      0.61        11\n\n    accuracy                           0.80        45\n   macro avg       0.78      0.79      0.78        45\nweighted avg       0.80      0.80      0.80        45\n'

In [21]:
linear = SVC(kernel = 'linear' , gamma = 1 , decision_function_shape = 'ovr')
linear.fit(X_train , y_train)

SVC(gamma=1, kernel='linear')

In [22]:
y_pred = linear.predict(X_test)

In [23]:
print("Linear kernel one vs one")

confusion_matrix(y_test , y_pred)

Linear kernel one vs one


array([[16,  0,  0],
       [ 0, 13,  5],
       [ 0,  4,  7]], dtype=int64)

In [24]:
classification_report(y_test , y_pred)

'              precision    recall  f1-score   support\n\n           0       1.00      1.00      1.00        16\n           1       0.76      0.72      0.74        18\n           2       0.58      0.64      0.61        11\n\n    accuracy                           0.80        45\n   macro avg       0.78      0.79      0.78        45\nweighted avg       0.80      0.80      0.80        45\n'